#! /bin/sh
#  Name
#$ -N diagfi

#  Use current working directory
#$ -cwd

#  Join stdout and stderr
#$ -j y

# job run time hours:min:sec (always over estimate)
#$ -l s_rt=300:00:00

#  Run job through bash shell
#$ -S /bin/bash

## Job
python diagfi_compare_singlemonth.py
